zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path:
    - "3 拼接相关"
    - "3 拼接相关/**"
    - "4 三维重建"
    - "4 三维重建/**"
    - "5 占据预测"
    - "5 占据预测/**"
  ignore_path: null # Or set a list of glob patterns, e.g. ["archive/**"]

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    model: deepseek-v4-flash
  language: Chinese

reranker:
  local:
    device: cuda

source:
  arxiv:
    category: ["cs.AI","cs.CV","cs.RO"]
    include_cross_list: false

executor:
  debug: false
  send_empty: true
  max_paper_num: 10
  source: ['arxiv']
  reranker: local

output:
  mode: markdown
  dir: outputs
  filename_template: "daily-arxiv-{date}.md"
